---
- name: Name Based Apache HTTP Server Configuration Playbook
  hosts: node1
  become: true
  tasks:
    - name: Setting up the static hostname in the server machine.
      hostname:
        name: node1.nehraclasses.com
        use: systemd

    - name: Making entries in the /etc/hosts file for the server hostname & IP Address
      lineinfile:
        dest: /etc/hosts
        line: 192.168.229.129 www.nehraclasses.com node1
        insertafter: EOF

    - name: Installing Apache packages in the machine.
      dnf:
        name:
          - httpd
        state: latest

    - name: Copying the image file to the /var/www/html/ directory.
      ansible.builtin.copy:
        src: /home/vikasnehra/NehraClassesLogo.png
        dest: /var/www/html/NehraClassesLogo.png
        mode: '0644'

    - name: Creating the website index file in the /var/www/html/ directory.
      copy:
        dest: "/var/www/html/index.html"
        content: |
          <img src="/NehraClassesLogo.png" width="500" height="500" />
          <h1>Nehra Classes Are Awesome.</h1>
          <i>This page is hosted on node1 using name-based Apache virtual hosting.</i>

    - name: Creating HTTPD configuration file in the /etc/httpd/conf.d/ directory.
      copy:
        dest: "/etc/httpd/conf.d/httpd.conf"
        content: |
          <VirtualHost 192.168.229.229:80>
          ServerAdmin root@node1.nehraclasses.com
          ServerAlias nehraclasses.com node1
          DocumentRoot /var/www/html/
          ServerName www.nehraclasses.com
          ErrorLog logs/www.nehraclasses.com-error_log
          CustomLog logs/www.nehraclasses.com-access_log common
          </VirtualHost>

    - name: Making changes in the /etc/httpd/conf/httpd.conf file for the name-based hosting.
      replace:
        dest: /etc/httpd/conf/httpd.conf
        regexp: '^#NameVirtualHost'
        replace: 'NameVirtualHost 192.168.229.129:80'

    - name: Allowing HTTPS traffic in the firewall.
      firewalld:
        service: http
        zone: public
        permanent: true
        immediate: true
        state: enabled

    - name: Starting & enabling the httpd service.
      service:
        name: httpd
        state: started
        enabled: yes
...
