---
- name: deleting a package
  hosts: all
  become: yes
  tasks:
    - name: Deleting the Apache2
      apt:
        name: apache2
        state: absent
      when: ansible_os_family == 'Debian'
    - name: Deleting the httpd 
      dnf:
        name: httpd
        state: absent
      when: ansible_os_family == 'RedHat'
...


