---
- name: MariaDB
  hosts: node1
  gather_facts: true
  become: true
  vars:
    mysql_root_password: "P@$$w0rd"
  tasks:
    - name: Dump database
      mysql_db:
        name: foo
        state: dump
        target: /tmp/foo.sql
        login_user: root
        login_password: "{{ mysql_root_password }}"
...
