---
- name: MariaDB
  hosts: node1
  gather_facts: true
  become: true
  vars:
    mysql_root_password: "P@$$w0rd"
  tasks:
      - name: Create new databases with names 'foo' and 'bar'
        mysql_db:
           name:
              - foo
              - bar
           state: present
           login_user: root
           login_password: "{{ mysql_root_password }}"
...

