---
- name: MariaDB
  hosts: node1
  gather_facts: true
  become: true
  tasks:
    - name: install mariadb
      yum:
        name:
          - mariadb-server
          - python3-PyMySQL
        state: latest

    - name: start mariadb
      service:
        name: mariadb
        enabled: true
        state: started
...
