---
- name: MariaDB
  hosts: node1
  gather_facts: true
  become: true
  vars:
    mysql_root_password: "P@$$w0rd"
  tasks:
    - name: Create a new database with name 'bobdata'
      mysql_db:
        name: bobdata
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"
...
